### ISSUE TITLE
aStar

### ISSUE THREAD

**Issue by qqtop** [zacharycarter/NimRL#1]
`nimrl/dungeon.nim(1, 8) Error: cannot open 'astar'`

**Comment by zacharycarter** [comment]
Please run a nimble install before trying to run the tests. Please let me know if that solves your issue.

**Comment by qqtop** [comment]
Confirm  aStar issue is ok now  but test still fails   
nim c  -r  test
now gives 

```Traceback (most recent call last)
test.nim(22)             test
test.nim(13)             main
nimrl.nim(120)           generate
nimrl.nim(92)            generateHBWDungeon
hbw.nim(55)              generate
read.nim(91)             load
Error: unhandled exception: can't fopen [STBIException]
Error: execution of an external program failed: '/data5/NimStuff/nimrl/tests/test '
``` 

only the caves are correctly displayed.

**Comment by zacharycarter** [comment]
Are you executing the examples from the root of the cloned repository? I probably should have mentioned that needs to be the case. If not, could you please try doing that?

If you are, could you please let me know what OS you're on so I can try to reproduce?

**Comment by qqtop** [comment]
Yes I tried both from root of cloned repo and from tests dir
same error message as stated above
OS : openSuse Tumbleweed 
Nim: latest devel

**Comment by qqtop** [comment]
After updating compiler to
```
$ nim -v
Nim Compiler Version 0.17.3 (2017-09-18) [Linux: amd64]
Copyright (c) 2006-2017 by Andreas Rumpf

active boot switches: -d:release
```
everything worked fine for me again
